### ISSUE TITLE
Fonts not getting assigned/bucketed correctly

### ISSUE THREAD

**Issue by MadLittleMods** [andyjansson/font-magician-directory#2]
I am trying to use the Urbano font stack with all of its condensed, ultra, etc versions.

Looking at the stacks in the cache, they are not using the right fonts. Here is the full [`font-magician.cache.json`](https://gist.github.com/anonymous/782fe38d20ce47d74791)

For example, "Urbano Light Condensed", these are the actual files it should reference:

 - Regular, weight 400: `Urbano-LightCond-webfont`
 - Italic, weight 400: `Urbano-LightCondItalic-webfont`

---

It also seems to add font-family rules for `font-family: FontAwesome;` in the CSS

```
@font-face {
	font-family: FontAwesome;
	font-weight: 900;
	font-style: italic;
	src: local("Urbano - Ultra Italic"),url(../fonts/Urbano-UltraItalic-webfont.eot?#) format("eot"),url(../fonts/Urbano-UltraItalic-webfont.ttf) format("ttf"),url(../fonts/Urbano-UltraItalic-webfont.woff) format("woff");
}

@font-face {
	font-family: FontAwesome;
	font-weight: 900;
	font-style: normal;
	src: local("Urbano - Ultra"),url(../fonts/Urbano-Ultra-webfont.eot?#) format("eot"),url(../fonts/Urbano-Ultra-webfont.ttf) format("ttf"),url(../fonts/Urbano-Ultra-webfont.woff) format("woff");
}

/* etc */
```

**Comment by andyjansson** [comment]
The latest check-ins should have solved the issue. Care to verify?

**Comment by MadLittleMods** [comment]
Looks like it is having the same issues.

It creates fonts for `FontAwesome`, `inherit`.

And it doesn't seem to match up the names quite correctly but this probably a problem with the font meta data itself.

**Comment by MadLittleMods** [comment]
@andyjansson was able to tackle the further issues.

But you should try deleting your `font-magician.cache.json` first.
